episode_length: 400
frame_skip: 4
mode: headless
model_urdf: /home/maractin/Workspace/soloRL/solo_description/robots/solo.urdf
control: torque
gains: null
task: walk
num_history_stack: 1
flat_ground: True
use_treadmill: True
