episode_length: 400
frame_skip: 4
mode: gui
model_urdf: /home/maractin/Workspace/soloRL/solo_description/robots/solo12.urdf
control: torque
gains: null
task: pointgoal
num_history_stack: 1
flat_ground: True
solo12: True
